name: interactive_editor
description: Editor for Fluter that does not use WebView.
version: 0.1.1
homepage: https://github.com/meg4cyberc4t/interactive_editor

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  file_picker: ^4.6.0
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
